[package]
name = "pulsebeam-simulator"
publish = false
version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dev-dependencies]
tokio.workspace = true
tokio-util.workspace = true
turmoil.workspace = true

pulsebeam = { version = "0.3.1", path = "../pulsebeam", features = ["sim"] }
pulsebeam-runtime = { version = "0.1.0", path = "../pulsebeam-runtime", features = ["sim"] }
pulsebeam-agent = { version = "0.1.0", path = "../pulsebeam-agent", features = ["sim"] }

proptest = "1.9.0"
test-strategy = "0.4.3"
