[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.3"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
  "aarch64-apple-darwin",
  "aarch64-unknown-linux-gnu",
  "x86_64-unknown-linux-gnu"
]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = true
# Plan jobs to run in CI
plan-jobs = ["./ci", "./docker"]

[dist.github-custom-job-permissions.docker]
actions = "read"
attestations = "write"
checks = "write"
contents = "write"
discussions = "read"
id-token = "write"
issues = "read"
packages = "write"
pull-requests = "read"
repository-projects = "read"
security-events = "read"
statuses = "read"

[dist.github-custom-runners]
global = "ubuntu-24.04"
x86_64-unknown-linux-gnu = "ubuntu-24.04"
aarch64-unknown-linux-gnu = "ubuntu-24.04-arm"
# x86_64-pc-windows-msvc = "windows-2025"
x86_64-pc-windows-msvc = "ubuntu-24.04"
aarch64-apple-darwin = "macos-15"

# https://axodotdev.github.io/cargo-dist/book/reference/config.html?highlight=dependencies#dependencies
[dist.dependencies.homebrew]
# Apple runner has this default
# clang = "*"
pkg-config = "*"
ffmpeg = "*"
protobuf = "*"
nasm = "*"

[dist.dependencies.apt]
build-essential = "*"
clang = "*"
pkg-config = "*"
protobuf-compiler = "*"
nasm = "*"
# ffmpeg dependencies
libavcodec-dev = "*"
libavformat-dev = "*"
libavutil-dev = "*"
libavfilter-dev = "*"
libavdevice-dev = "*"

[dist.dependencies.chocolatey]
msys2 = "*"  # like build-essential on ubuntu
llvm = "*"
ffmpeg = "*"
protoc = "*"
nasm = "*"
