[toolchain]
channel = "1.92.0"
profile = "minimal"
components = ["rustfmt", "clippy", "rust-src", "rust-analyzer"]

# https://internals.rust-lang.org/t/bundle-zig-cc-in-rustup-by-default/22096
# In the future, Rust might just ship with zig by default!
