[package]
name = "pulsebeam"
version = "0.2.22"

edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
str0m = { workspace = true }
bytes = { workspace = true }
rand = { workspace = true } 

tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
axum = { version = "0.8.7", features = ["macros"] }
axum-extra = { version = "0.12.2", features = ["typed-header"] }
systemstat = "0.2.5"
tower-http = { version = "0.6.7", features = ["cors"] }
hex = "0.4.3"
prost = "0.14.1"
bs58 = "0.5.1"
sha3 = "0.10.8"
metrics = "0.24.3"
mimalloc = { version = "0.1.48", features = ["v3"] }
hyper = "1.8.1"
pulsebeam-runtime = { version = "^0.1.0", path = "../pulsebeam-runtime" }
tokio-util = "0.7.17"
num_cpus = "1.17.0"
metrics-exporter-prometheus = "0.18.0"
pprof = { version = "0.15.0", features = ["flamegraph", "prost-codec", "protobuf"] }
tokio-metrics = { version = "0.4.5", features = ["metrics-rs-integration"] }
once_cell = "1.21.3"
ahash = "0.8.12"

[dev-dependencies]
turmoil = "0.7.0"

[build-dependencies]
prost-build = "0.14.1"


# Windows-specific str0m override
[target.'cfg(windows)'.dependencies]
str0m = { workspace = true, features = ["wincrypto"] }
